"""initial schema

Creates every table in `boat_prediction.db.models`: the guide's §6.2/§7.2
tables that the parsed B-file and K-file sources can fill, plus
`race_payouts`. See that module's docstring for the deviations from the
guide's listing and why each one exists.

Forward: creates tables only, no data motion, so it is safe on an empty
database and there is nothing to lock.
Rollback: `alembic downgrade base` drops them all. Because this is the
initial revision, rolling back destroys every loaded row -- the archive
under `data/raw/boatrace/` is the source of truth and a full re-load
rebuilds the database from it.

Revision ID: 3997a65d30a7
Revises: 
Create Date: 2026-07-31 09:51:20.449938
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '3997a65d30a7'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=200), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=True),
    sa.Column('terms_url', sa.Text(), nullable=True),
    sa.Column('acquisition_method', sa.String(length=100), nullable=True),
    sa.Column('update_frequency', sa.String(length=100), nullable=True),
    sa.Column('license_note', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_sources')),
    sa.UniqueConstraint('code', name=op.f('uq_data_sources_code'))
    )
    op.create_table('racers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('registration_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('branch', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_racers')),
    sa.UniqueConstraint('registration_number', name=op.f('uq_racers_registration_number'))
    )
    op.create_table('venues',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_venues')),
    sa.UniqueConstraint('code', name=op.f('uq_venues_code'))
    )
    op.create_table('race_meetings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('meeting_start_date', sa.Date(), nullable=False),
    sa.Column('meeting_end_date', sa.Date(), nullable=True),
    sa.Column('meeting_title', sa.String(length=200), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_race_meetings_source_id')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_race_meetings_venue_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_meetings')),
    sa.UniqueConstraint('venue_id', 'meeting_start_date', name=op.f('uq_race_meetings_venue_id_meeting_start_date'))
    )
    op.create_table('races',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('race_number', sa.SmallInteger(), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('scheduled_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_fixed_entry', sa.Boolean(), nullable=True),
    sa.Column('race_class_label', sa.String(length=50), nullable=True),
    sa.Column('race_class', sa.String(length=50), nullable=True),
    sa.Column('series_day', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('race_number BETWEEN 1 AND 12', name=op.f('ck_races_race_number_range')),
    sa.ForeignKeyConstraint(['meeting_id'], ['race_meetings.id'], name=op.f('fk_races_meeting_id')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_races_venue_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_races')),
    sa.UniqueConstraint('race_date', 'venue_id', 'race_number', name=op.f('uq_races_race_date_venue_id_race_number'))
    )
    op.create_index(op.f('ix_races_race_class'), 'races', ['race_class'], unique=False)
    op.create_index(op.f('ix_races_race_date'), 'races', ['race_date'], unique=False)
    op.create_index(op.f('ix_races_venue_id'), 'races', ['venue_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=False),
    sa.Column('combination', sa.String(length=20), nullable=False),
    sa.Column('odds', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=True),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_odds_snapshots_race_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_odds_snapshots_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_odds_snapshots')),
    sa.UniqueConstraint('race_id', 'bet_type', 'combination', 'observed_at', name=op.f('uq_odds_snapshots_race_id_bet_type_combination_observed_at'))
    )
    op.create_table('race_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('lane_number', sa.SmallInteger(), nullable=False),
    sa.Column('racer_id', sa.Uuid(), nullable=False),
    sa.Column('listed_class', sa.String(length=10), nullable=True),
    sa.Column('listed_age', sa.SmallInteger(), nullable=True),
    sa.Column('listed_branch', sa.String(length=20), nullable=True),
    sa.Column('listed_weight', sa.SmallInteger(), nullable=True),
    sa.Column('listed_national_win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('listed_national_second_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('listed_local_win_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('listed_local_second_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('listed_average_st', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('listed_motor_number', sa.SmallInteger(), nullable=True),
    sa.Column('listed_motor_second_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('listed_boat_number', sa.SmallInteger(), nullable=True),
    sa.Column('listed_boat_second_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('listed_series_form_raw', sa.String(length=20), nullable=True),
    sa.Column('source_published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lane_number BETWEEN 1 AND 6', name=op.f('ck_race_entries_lane_number_range')),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_entries_race_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['racer_id'], ['racers.id'], name=op.f('fk_race_entries_racer_id')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_race_entries_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_entries')),
    sa.UniqueConstraint('race_id', 'lane_number', name=op.f('uq_race_entries_race_id_lane_number'))
    )
    op.create_index(op.f('ix_race_entries_racer_id'), 'race_entries', ['racer_id'], unique=False)
    op.create_table('race_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('winning_method', sa.String(length=20), nullable=True),
    sa.Column('is_refund', sa.Boolean(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_results_race_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_race_results_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_results')),
    sa.UniqueConstraint('race_id', name=op.f('uq_race_results_race_id'))
    )
    op.create_table('exhibition_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_entry_id', sa.Uuid(), nullable=False),
    sa.Column('exhibition_course', sa.SmallInteger(), nullable=True),
    sa.Column('exhibition_time_sec', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('exhibition_st_sec', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tilt_angle', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['race_entry_id'], ['race_entries.id'], name=op.f('fk_exhibition_entries_race_entry_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_exhibition_entries_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exhibition_entries')),
    sa.UniqueConstraint('race_entry_id', name=op.f('uq_exhibition_entries_race_entry_id'))
    )
    op.create_table('race_payouts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_result_id', sa.Uuid(), nullable=False),
    sa.Column('bet_type', sa.String(length=20), nullable=False),
    sa.Column('combination', sa.String(length=20), nullable=False),
    sa.Column('payout_yen', sa.Integer(), nullable=True),
    sa.Column('popularity_rank', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['race_result_id'], ['race_results.id'], name=op.f('fk_race_payouts_race_result_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_payouts')),
    sa.UniqueConstraint('race_result_id', 'bet_type', 'combination', name=op.f('uq_race_payouts_race_result_id_bet_type_combination'))
    )
    op.create_table('race_result_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_result_id', sa.Uuid(), nullable=False),
    sa.Column('race_entry_id', sa.Uuid(), nullable=True),
    sa.Column('lane_number', sa.SmallInteger(), nullable=False),
    sa.Column('racer_registration_number', sa.Integer(), nullable=True),
    sa.Column('actual_course', sa.SmallInteger(), nullable=True),
    sa.Column('actual_st_sec', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('finish_position', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('race_time_raw', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lane_number BETWEEN 1 AND 6', name=op.f('ck_race_result_entries_lane_number_range')),
    sa.ForeignKeyConstraint(['race_entry_id'], ['race_entries.id'], name=op.f('fk_race_result_entries_race_entry_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['race_result_id'], ['race_results.id'], name=op.f('fk_race_result_entries_race_result_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_result_entries')),
    sa.UniqueConstraint('race_result_id', 'lane_number', name=op.f('uq_race_result_entries_race_result_id_lane_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_result_entries')
    op.drop_table('race_payouts')
    op.drop_table('exhibition_entries')
    op.drop_table('race_results')
    op.drop_index(op.f('ix_race_entries_racer_id'), table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_races_venue_id'), table_name='races')
    op.drop_index(op.f('ix_races_race_date'), table_name='races')
    op.drop_index(op.f('ix_races_race_class'), table_name='races')
    op.drop_table('races')
    op.drop_table('race_meetings')
    op.drop_table('venues')
    op.drop_table('racers')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
