"""add beforeinfo tables

Revision ID: 57a2b01ded66
Revises: d0666c2c2a13
Create Date: 2026-08-01 12:51:38.331157
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '57a2b01ded66'
down_revision: str | None = 'd0666c2c2a13'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('before_info_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('lane_number', sa.SmallInteger(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('adjustment_weight_kg', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('exhibition_time_sec', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('tilt_angle', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('propeller_changed', sa.Boolean(), nullable=True),
    sa.Column('parts_replaced', sa.Text(), nullable=True),
    sa.Column('start_exhibition_course', sa.SmallInteger(), nullable=True),
    sa.Column('start_exhibition_st_sec', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('start_exhibition_is_flying', sa.Boolean(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_before_info_entries_race_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_before_info_entries_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_before_info_entries')),
    sa.UniqueConstraint('race_id', 'lane_number', 'observed_at', name=op.f('uq_before_info_entries_race_id_lane_number_observed_at'))
    )
    op.create_index(op.f('ix_before_info_entries_race_id'), 'before_info_entries', ['race_id'], unique=False)
    op.create_table('race_surface_conditions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('race_id', sa.Uuid(), nullable=False),
    sa.Column('raw_label', sa.String(length=40), nullable=True),
    sa.Column('reference_race_number', sa.SmallInteger(), nullable=True),
    sa.Column('air_temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('water_temperature_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_speed_ms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_direction_code', sa.SmallInteger(), nullable=True),
    sa.Column('wave_height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weather_text', sa.String(length=20), nullable=True),
    sa.Column('weather_icon_code', sa.SmallInteger(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], name=op.f('fk_race_surface_conditions_race_id'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_race_surface_conditions_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_race_surface_conditions')),
    sa.UniqueConstraint('race_id', 'observed_at', name=op.f('uq_race_surface_conditions_race_id_observed_at'))
    )
    op.create_index(op.f('ix_race_surface_conditions_race_id'), 'race_surface_conditions', ['race_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_race_surface_conditions_race_id'), table_name='race_surface_conditions')
    op.drop_table('race_surface_conditions')
    op.drop_index(op.f('ix_before_info_entries_race_id'), table_name='before_info_entries')
    op.drop_table('before_info_entries')
    # ### end Alembic commands ###
