"""add weather_observations table

Adds the table `boat_prediction.db.loader.load_weather_month` writes,
one row per (venue, day) JMA daily summary -- see that module's
`WeatherObservation` docstring for the schema and
`load_jma_archive.py` for the batch driver.

Forward: creates one new table with FKs to the existing `venues` and
`data_sources` tables; no existing table is touched, so this is safe
to apply against a database with data already loaded.
Rollback: `alembic downgrade -1` drops the table and its index. Because
nothing else references `weather_observations`, this destroys only
loaded weather rows -- re-running `load_jma_archive.py` rebuilds them
from the archive under `data/raw/boatrace/jma/`.

Revision ID: 9e24c5ea64e2
Revises: 3997a65d30a7
Create Date: 2026-07-31 12:27:48.812253
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '9e24c5ea64e2'
down_revision: str | None = '3997a65d30a7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venue_id', sa.Uuid(), nullable=False),
    sa.Column('weather_date', sa.Date(), nullable=False),
    sa.Column('precipitation_total_mm', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('precipitation_max_1h_mm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('precipitation_max_10min_mm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('temperature_avg_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temperature_max_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temperature_min_c', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('humidity_avg_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('humidity_min_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_avg_ms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_max_ms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_max_direction', sa.String(length=10), nullable=True),
    sa.Column('wind_max_instant_ms', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('wind_max_instant_direction', sa.String(length=10), nullable=True),
    sa.Column('wind_prevailing_direction', sa.String(length=10), nullable=True),
    sa.Column('sunshine_hours', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_weather_observations_source_id')),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], name=op.f('fk_weather_observations_venue_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weather_observations')),
    sa.UniqueConstraint('venue_id', 'weather_date', name=op.f('uq_weather_observations_venue_id_weather_date'))
    )
    op.create_index(op.f('ix_weather_observations_venue_id'), 'weather_observations', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_observations_venue_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    # ### end Alembic commands ###
