"""add racer period stats tables

Revision ID: aa3047500d13
Revises: 9e24c5ea64e2
Create Date: 2026-08-01 11:29:10.168823
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'aa3047500d13'
down_revision: str | None = '9e24c5ea64e2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('racer_period_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('racer_id', sa.Uuid(), nullable=False),
    sa.Column('period_year', sa.SmallInteger(), nullable=False),
    sa.Column('period_number', sa.SmallInteger(), nullable=False),
    sa.Column('period_from', sa.Date(), nullable=True),
    sa.Column('period_to', sa.Date(), nullable=True),
    sa.Column('racer_class', sa.String(length=5), nullable=True),
    sa.Column('prev_class', sa.String(length=5), nullable=True),
    sa.Column('prev2_class', sa.String(length=5), nullable=True),
    sa.Column('prev3_class', sa.String(length=5), nullable=True),
    sa.Column('prev_ability_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('current_ability_index', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('place_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('first_place_count', sa.Integer(), nullable=True),
    sa.Column('second_place_count', sa.Integer(), nullable=True),
    sa.Column('start_count', sa.Integer(), nullable=True),
    sa.Column('championship_appearance_count', sa.Integer(), nullable=True),
    sa.Column('championship_win_count', sa.Integer(), nullable=True),
    sa.Column('avg_start_timing', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('height_cm', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.SmallInteger(), nullable=True),
    sa.Column('blood_type', sa.String(length=4), nullable=True),
    sa.Column('branch', sa.String(length=20), nullable=True),
    sa.Column('hometown', sa.String(length=20), nullable=True),
    sa.Column('no_course_l0_count', sa.Integer(), nullable=True),
    sa.Column('no_course_l1_count', sa.Integer(), nullable=True),
    sa.Column('no_course_k0_count', sa.Integer(), nullable=True),
    sa.Column('no_course_k1_count', sa.Integer(), nullable=True),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['racer_id'], ['racers.id'], name=op.f('fk_racer_period_stats_racer_id')),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_racer_period_stats_source_id')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_racer_period_stats')),
    sa.UniqueConstraint('racer_id', 'period_year', 'period_number', name=op.f('uq_racer_period_stats_racer_id_period_year_period_number'))
    )
    op.create_index(op.f('ix_racer_period_stats_racer_id'), 'racer_period_stats', ['racer_id'], unique=False)
    op.create_table('racer_period_course_stats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('racer_period_stats_id', sa.Uuid(), nullable=False),
    sa.Column('course_number', sa.SmallInteger(), nullable=False),
    sa.Column('entry_count', sa.Integer(), nullable=True),
    sa.Column('place_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_start_timing', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('avg_start_rank', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('finish_1_count', sa.Integer(), nullable=True),
    sa.Column('finish_2_count', sa.Integer(), nullable=True),
    sa.Column('finish_3_count', sa.Integer(), nullable=True),
    sa.Column('finish_4_count', sa.Integer(), nullable=True),
    sa.Column('finish_5_count', sa.Integer(), nullable=True),
    sa.Column('finish_6_count', sa.Integer(), nullable=True),
    sa.Column('f_count', sa.Integer(), nullable=True),
    sa.Column('l0_count', sa.Integer(), nullable=True),
    sa.Column('l1_count', sa.Integer(), nullable=True),
    sa.Column('k0_count', sa.Integer(), nullable=True),
    sa.Column('k1_count', sa.Integer(), nullable=True),
    sa.Column('s0_count', sa.Integer(), nullable=True),
    sa.Column('s1_count', sa.Integer(), nullable=True),
    sa.Column('s2_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['racer_period_stats_id'], ['racer_period_stats.id'], name=op.f('fk_racer_period_course_stats_racer_period_stats_id'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_racer_period_course_stats')),
    sa.UniqueConstraint('racer_period_stats_id', 'course_number', name=op.f('uq_racer_period_course_stats_racer_period_stats_id_course_number'))
    )
    op.create_index(op.f('ix_racer_period_course_stats_racer_period_stats_id'), 'racer_period_course_stats', ['racer_period_stats_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_racer_period_course_stats_racer_period_stats_id'), table_name='racer_period_course_stats')
    op.drop_table('racer_period_course_stats')
    op.drop_index(op.f('ix_racer_period_stats_racer_id'), table_name='racer_period_stats')
    op.drop_table('racer_period_stats')
    # ### end Alembic commands ###
